// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AskReducer from "../ask_reducer";
import CreateRoomReducer from "../create_room_reducer";
import GoDeeperReducer from "../go_deeper_reducer";
import JoinRoomReducer from "../join_room_reducer";
import LeaveRoomReducer from "../leave_room_reducer";
import PostNoteReducer from "../post_note_reducer";
import RequestVerdictEmailReducer from "../request_verdict_email_reducer";
import SetKillSwitchReducer from "../set_kill_switch_reducer";
import SetLimitsReducer from "../set_limits_reducer";
import SetModelSlotReducer from "../set_model_slot_reducer";
import SetProviderKeyReducer from "../set_provider_key_reducer";
import WrapUpReducer from "../wrap_up_reducer";

export type AskParams = __Infer<typeof AskReducer>;
export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type GoDeeperParams = __Infer<typeof GoDeeperReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type LeaveRoomParams = __Infer<typeof LeaveRoomReducer>;
export type PostNoteParams = __Infer<typeof PostNoteReducer>;
export type RequestVerdictEmailParams = __Infer<typeof RequestVerdictEmailReducer>;
export type SetKillSwitchParams = __Infer<typeof SetKillSwitchReducer>;
export type SetLimitsParams = __Infer<typeof SetLimitsReducer>;
export type SetModelSlotParams = __Infer<typeof SetModelSlotReducer>;
export type SetProviderKeyParams = __Infer<typeof SetProviderKeyReducer>;
export type WrapUpParams = __Infer<typeof WrapUpReducer>;

