// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  questionId: __t.u64().name("question_id"),
  round: __t.u32(),
  slot: __t.string(),
  label: __t.string(),
  model: __t.string(),
  text: __t.string(),
  assumptions: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  latencyMs: __t.u32().name("latency_ms"),
  ok: __t.bool(),
});
