// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  questionId: __t.u64().name("question_id"),
  objectionId: __t.u64().name("objection_id"),
  targetOrdinal: __t.u32().name("target_ordinal"),
  claim: __t.string(),
  verdict: __t.string(),
  url: __t.string(),
  title: __t.string(),
  excerpt: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
