// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.0 (commit baca5cdf77577ed4e3f30da48a5158189c4ea43f).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AskReducer from "./ask_reducer";
import CreateRoomReducer from "./create_room_reducer";
import GoDeeperReducer from "./go_deeper_reducer";
import JoinRoomReducer from "./join_room_reducer";
import LeaveRoomReducer from "./leave_room_reducer";
import OpenRoomReducer from "./open_room_reducer";
import PostNoteReducer from "./post_note_reducer";
import RequestJoinEmailReducer from "./request_join_email_reducer";
import RequestVerdictEmailReducer from "./request_verdict_email_reducer";
import SetEmailProviderReducer from "./set_email_provider_reducer";
import SetKillSwitchReducer from "./set_kill_switch_reducer";
import SetLimitsReducer from "./set_limits_reducer";
import SetModelSlotReducer from "./set_model_slot_reducer";
import SetProviderKeyReducer from "./set_provider_key_reducer";
import SetSiteUrlReducer from "./set_site_url_reducer";
import StartWatchdogReducer from "./start_watchdog_reducer";
import WrapUpReducer from "./wrap_up_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import AgentEventRow from "./agent_event_table";
import AgentStatusRow from "./agent_status_table";
import AnswerVersionRow from "./answer_version_table";
import DraftRow from "./draft_table";
import EvidenceRow from "./evidence_table";
import MemberRow from "./member_table";
import ModelSlotRow from "./model_slot_table";
import NoteRow from "./note_table";
import ObjectionRow from "./objection_table";
import ParagraphRow from "./paragraph_table";
import QuestionRow from "./question_table";
import RoomRow from "./room_table";
import TeamQuestionRow from "./team_question_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  agentEvent: __table({
    name: 'agent_event',
    indexes: [
      { accessor: 'id', name: 'agent_event_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'questionId', name: 'agent_event_question_id_idx_btree', algorithm: 'btree', columns: [
        'questionId',
      ] },
    ],
    constraints: [
      { name: 'agent_event_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AgentEventRow),
  agentStatus: __table({
    name: 'agent_status',
    indexes: [
      { accessor: 'id', name: 'agent_status_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'questionId', name: 'agent_status_question_id_idx_btree', algorithm: 'btree', columns: [
        'questionId',
      ] },
    ],
    constraints: [
      { name: 'agent_status_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AgentStatusRow),
  answerVersion: __table({
    name: 'answer_version',
    indexes: [
      { accessor: 'id', name: 'answer_version_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'questionId', name: 'answer_version_question_id_idx_btree', algorithm: 'btree', columns: [
        'questionId',
      ] },
    ],
    constraints: [
      { name: 'answer_version_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AnswerVersionRow),
  draft: __table({
    name: 'draft',
    indexes: [
      { accessor: 'id', name: 'draft_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'questionId', name: 'draft_question_id_idx_btree', algorithm: 'btree', columns: [
        'questionId',
      ] },
    ],
    constraints: [
      { name: 'draft_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DraftRow),
  evidence: __table({
    name: 'evidence',
    indexes: [
      { accessor: 'id', name: 'evidence_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'questionId', name: 'evidence_question_id_idx_btree', algorithm: 'btree', columns: [
        'questionId',
      ] },
    ],
    constraints: [
      { name: 'evidence_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EvidenceRow),
  member: __table({
    name: 'member',
    indexes: [
      { accessor: 'id', name: 'member_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'identity', name: 'member_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'by_room_identity', name: 'member_room_id_identity_idx_btree', algorithm: 'btree', columns: [
        'roomId',
        'identity',
      ] },
      { accessor: 'roomId', name: 'member_room_id_idx_btree', algorithm: 'btree', columns: [
        'roomId',
      ] },
    ],
    constraints: [
      { name: 'member_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MemberRow),
  modelSlot: __table({
    name: 'model_slot',
    indexes: [
      { accessor: 'slot', name: 'model_slot_slot_idx_btree', algorithm: 'btree', columns: [
        'slot',
      ] },
    ],
    constraints: [
      { name: 'model_slot_slot_key', constraint: 'unique', columns: ['slot'] },
    ],
  }, ModelSlotRow),
  note: __table({
    name: 'note',
    indexes: [
      { accessor: 'id', name: 'note_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'questionId', name: 'note_question_id_idx_btree', algorithm: 'btree', columns: [
        'questionId',
      ] },
      { accessor: 'roomId', name: 'note_room_id_idx_btree', algorithm: 'btree', columns: [
        'roomId',
      ] },
    ],
    constraints: [
      { name: 'note_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, NoteRow),
  objection: __table({
    name: 'objection',
    indexes: [
      { accessor: 'id', name: 'objection_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'questionId', name: 'objection_question_id_idx_btree', algorithm: 'btree', columns: [
        'questionId',
      ] },
    ],
    constraints: [
      { name: 'objection_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ObjectionRow),
  paragraph: __table({
    name: 'paragraph',
    indexes: [
      { accessor: 'id', name: 'paragraph_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_question_current', name: 'paragraph_question_id_current_idx_btree', algorithm: 'btree', columns: [
        'questionId',
        'current',
      ] },
      { accessor: 'questionId', name: 'paragraph_question_id_idx_btree', algorithm: 'btree', columns: [
        'questionId',
      ] },
    ],
    constraints: [
      { name: 'paragraph_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ParagraphRow),
  question: __table({
    name: 'question',
    indexes: [
      { accessor: 'id', name: 'question_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'roomId', name: 'question_room_id_idx_btree', algorithm: 'btree', columns: [
        'roomId',
      ] },
    ],
    constraints: [
      { name: 'question_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, QuestionRow),
  room: __table({
    name: 'room',
    indexes: [
      { accessor: 'code', name: 'room_code_idx_btree', algorithm: 'btree', columns: [
        'code',
      ] },
      { accessor: 'id', name: 'room_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'room_code_key', constraint: 'unique', columns: ['code'] },
      { name: 'room_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RoomRow),
  teamQuestion: __table({
    name: 'team_question',
    indexes: [
      { accessor: 'id', name: 'team_question_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'questionId', name: 'team_question_question_id_idx_btree', algorithm: 'btree', columns: [
        'questionId',
      ] },
      { accessor: 'roomId', name: 'team_question_room_id_idx_btree', algorithm: 'btree', columns: [
        'roomId',
      ] },
    ],
    constraints: [
      { name: 'team_question_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TeamQuestionRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("ask", AskReducer),
  __reducerSchema("create_room", CreateRoomReducer),
  __reducerSchema("go_deeper", GoDeeperReducer),
  __reducerSchema("join_room", JoinRoomReducer),
  __reducerSchema("leave_room", LeaveRoomReducer),
  __reducerSchema("open_room", OpenRoomReducer),
  __reducerSchema("post_note", PostNoteReducer),
  __reducerSchema("request_join_email", RequestJoinEmailReducer),
  __reducerSchema("request_verdict_email", RequestVerdictEmailReducer),
  __reducerSchema("set_email_provider", SetEmailProviderReducer),
  __reducerSchema("set_kill_switch", SetKillSwitchReducer),
  __reducerSchema("set_limits", SetLimitsReducer),
  __reducerSchema("set_model_slot", SetModelSlotReducer),
  __reducerSchema("set_provider_key", SetProviderKeyReducer),
  __reducerSchema("set_site_url", SetSiteUrlReducer),
  __reducerSchema("start_watchdog", StartWatchdogReducer),
  __reducerSchema("wrap_up", WrapUpReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

type __SchemaWithTableAccessorAliases = Omit<typeof tablesSchema.schemaType, "tables"> & {
  tables: typeof tablesSchema.schemaType.tables & {
    /** @deprecated Use `agentEvent` instead. This alias will be removed in the next major version. */
    readonly "agent_event": Omit<typeof tablesSchema.schemaType.tables["agentEvent"], "accessorName"> & { readonly accessorName: "agent_event" };
    /** @deprecated Use `agentStatus` instead. This alias will be removed in the next major version. */
    readonly "agent_status": Omit<typeof tablesSchema.schemaType.tables["agentStatus"], "accessorName"> & { readonly accessorName: "agent_status" };
    /** @deprecated Use `answerVersion` instead. This alias will be removed in the next major version. */
    readonly "answer_version": Omit<typeof tablesSchema.schemaType.tables["answerVersion"], "accessorName"> & { readonly accessorName: "answer_version" };
    /** @deprecated Use `modelSlot` instead. This alias will be removed in the next major version. */
    readonly "model_slot": Omit<typeof tablesSchema.schemaType.tables["modelSlot"], "accessorName"> & { readonly accessorName: "model_slot" };
    /** @deprecated Use `teamQuestion` instead. This alias will be removed in the next major version. */
    readonly "team_question": Omit<typeof tablesSchema.schemaType.tables["teamQuestion"], "accessorName"> & { readonly accessorName: "team_question" };
  };
};

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.10.0" as const,
  },
  tables: tablesSchema.schemaType.tables as __SchemaWithTableAccessorAliases["tables"],
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  __SchemaWithTableAccessorAliases,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

const tableAccessorAliases = {
  "agent_event": "agentEvent",
  "agent_status": "agentStatus",
  "answer_version": "answerVersion",
  "model_slot": "modelSlot",
  "team_question": "teamQuestion",
} as const;

function __withTableAccessorAliases<T extends object>(target: T, freeze = false): T {
  const out = Object.create(Object.getPrototypeOf(target)) as T & Record<string, unknown>;
  Object.defineProperties(out, Object.getOwnPropertyDescriptors(target));
  for (const [deprecatedAccessor, targetAccessor] of Object.entries(tableAccessorAliases)) {
    if (deprecatedAccessor in out) {
      continue;
    }
    Object.defineProperty(out, deprecatedAccessor, {
      enumerable: true,
      configurable: false,
      get: () => out[targetAccessor],
    });
  }
  return freeze ? Object.freeze(out) : out;
}

type __DbViewBase = __DbConnectionImpl<typeof REMOTE_MODULE>["db"];
export type DbView = __DbViewBase & {
  /** @deprecated Use `agentEvent` instead. This alias will be removed in the next major version. */
  readonly "agent_event": __DbViewBase["agentEvent"];
  /** @deprecated Use `agentStatus` instead. This alias will be removed in the next major version. */
  readonly "agent_status": __DbViewBase["agentStatus"];
  /** @deprecated Use `answerVersion` instead. This alias will be removed in the next major version. */
  readonly "answer_version": __DbViewBase["answerVersion"];
  /** @deprecated Use `modelSlot` instead. This alias will be removed in the next major version. */
  readonly "model_slot": __DbViewBase["modelSlot"];
  /** @deprecated Use `teamQuestion` instead. This alias will be removed in the next major version. */
  readonly "team_question": __DbViewBase["teamQuestion"];
};

type __TablesBase = __QueryBuilder<typeof tablesSchema.schemaType>;
export type Tables = __TablesBase & {
  /** @deprecated Use `agentEvent` instead. This alias will be removed in the next major version. */
  readonly "agent_event": __TablesBase["agentEvent"];
  /** @deprecated Use `agentStatus` instead. This alias will be removed in the next major version. */
  readonly "agent_status": __TablesBase["agentStatus"];
  /** @deprecated Use `answerVersion` instead. This alias will be removed in the next major version. */
  readonly "answer_version": __TablesBase["answerVersion"];
  /** @deprecated Use `modelSlot` instead. This alias will be removed in the next major version. */
  readonly "model_slot": __TablesBase["modelSlot"];
  /** @deprecated Use `teamQuestion` instead. This alias will be removed in the next major version. */
  readonly "team_question": __TablesBase["teamQuestion"];
};

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
const tablesBase: __TablesBase = __makeQueryBuilder(tablesSchema.schemaType);
export const tables: Tables = __withTableAccessorAliases(tablesBase, true) as Tables;

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = Omit<__EventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = Omit<__ReducerEventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = Omit<__SubscriptionEventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for error events. */
export type ErrorContext = Omit<__ErrorContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  declare db: DbView;

  constructor(config: __DbConnectionConfig<typeof REMOTE_MODULE>) {
    super(config);
    this.db = __withTableAccessorAliases(this.db) as DbView;
  }

  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

