// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roomId: __t.u64().name("room_id"),
  questionId: __t.u64().name("question_id"),
  teamQuestionId: __t.u64().name("team_question_id"),
  author: __t.identity(),
  authorName: __t.string().name("author_name"),
  text: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  consumedStep: __t.string().name("consumed_step"),
  consumedRound: __t.u32().name("consumed_round"),
});
