// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  questionId: __t.u64().name("question_id"),
  round: __t.u32(),
  bySlot: __t.string().name("by_slot"),
  byLabel: __t.string().name("by_label"),
  targetOrdinal: __t.u32().name("target_ordinal"),
  claim: __t.string(),
  issue: __t.string(),
  checkable: __t.bool(),
  severity: __t.u8(),
  status: __t.string(),
  resolution: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
