// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  questionId: __t.u64().name("question_id"),
  ordinal: __t.u32(),
  version: __t.u32(),
  text: __t.string(),
  status: __t.string(),
  causeType: __t.string().name("cause_type"),
  causeId: __t.u64().name("cause_id"),
  why: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  current: __t.bool(),
  heading: __t.string(),
});
