// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roomId: __t.u64().name("room_id"),
  askedBy: __t.identity().name("asked_by"),
  askedByName: __t.string().name("asked_by_name"),
  text: __t.string(),
  state: __t.string(),
  round: __t.u32(),
  roundCap: __t.u32().name("round_cap"),
  version: __t.u32(),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  settledAt: __t.option(__t.timestamp()).name("settled_at"),
  wrapRequested: __t.bool().name("wrap_requested"),
  callsUsed: __t.u32().name("calls_used"),
  openObjections: __t.u32().name("open_objections"),
  lastError: __t.string().name("last_error"),
});
