// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  questionId: __t.u64().name("question_id"),
  roomId: __t.u64().name("room_id"),
  text: __t.string(),
  answer: __t.string(),
  answeredByName: __t.string().name("answered_by_name"),
  createdAt: __t.timestamp().name("created_at"),
  answeredAt: __t.option(__t.timestamp()).name("answered_at"),
});
