// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AgentEvent = __t.object("AgentEvent", {
  id: __t.u64(),
  questionId: __t.u64(),
  slot: __t.string(),
  kind: __t.string(),
  detail: __t.string(),
  url: __t.string(),
  createdAt: __t.timestamp(),
});
export type AgentEvent = __Infer<typeof AgentEvent>;

export const AgentStatus = __t.object("AgentStatus", {
  id: __t.u64(),
  questionId: __t.u64(),
  slot: __t.string(),
  state: __t.string(),
  detail: __t.string(),
  updatedAt: __t.timestamp(),
});
export type AgentStatus = __Infer<typeof AgentStatus>;

export const AnswerVersion = __t.object("AnswerVersion", {
  id: __t.u64(),
  questionId: __t.u64(),
  version: __t.u32(),
  round: __t.u32(),
  summary: __t.string(),
  createdAt: __t.timestamp(),
});
export type AnswerVersion = __Infer<typeof AnswerVersion>;

export const Config = __t.object("Config", {
  id: __t.u32(),
  owner: __t.identity(),
  killSwitch: __t.bool(),
  maxCallsPerQuestion: __t.u32(),
  maxQuestionsPerRoom: __t.u32(),
  maxMembersPerRoom: __t.u32(),
  defaultRoundCap: __t.u32(),
  siteUrl: __t.string(),
});
export type Config = __Infer<typeof Config>;

export const Draft = __t.object("Draft", {
  id: __t.u64(),
  questionId: __t.u64(),
  round: __t.u32(),
  slot: __t.string(),
  label: __t.string(),
  model: __t.string(),
  text: __t.string(),
  assumptions: __t.string(),
  createdAt: __t.timestamp(),
  latencyMs: __t.u32(),
  ok: __t.bool(),
});
export type Draft = __Infer<typeof Draft>;

export const EmailRequest = __t.object("EmailRequest", {
  id: __t.u64(),
  roomId: __t.u64(),
  questionId: __t.u64(),
  email: __t.string(),
  createdAt: __t.timestamp(),
  sentAt: __t.option(__t.timestamp()),
  status: __t.string(),
});
export type EmailRequest = __Infer<typeof EmailRequest>;

export const Evidence = __t.object("Evidence", {
  id: __t.u64(),
  questionId: __t.u64(),
  objectionId: __t.u64(),
  targetOrdinal: __t.u32(),
  claim: __t.string(),
  verdict: __t.string(),
  url: __t.string(),
  title: __t.string(),
  excerpt: __t.string(),
  createdAt: __t.timestamp(),
});
export type Evidence = __Infer<typeof Evidence>;

export const Member = __t.object("Member", {
  id: __t.u64(),
  roomId: __t.u64(),
  identity: __t.identity(),
  name: __t.string(),
  joinedAt: __t.timestamp(),
  lastSeen: __t.timestamp(),
  online: __t.bool(),
});
export type Member = __Infer<typeof Member>;

export const ModelSlot = __t.object("ModelSlot", {
  slot: __t.string(),
  model: __t.string(),
  label: __t.string(),
  providerId: __t.u32(),
  useWeb: __t.bool(),
  enabled: __t.bool(),
  reasoning: __t.string(),
  jsonMode: __t.string(),
});
export type ModelSlot = __Infer<typeof ModelSlot>;

export const Note = __t.object("Note", {
  id: __t.u64(),
  roomId: __t.u64(),
  questionId: __t.u64(),
  teamQuestionId: __t.u64(),
  author: __t.identity(),
  authorName: __t.string(),
  text: __t.string(),
  createdAt: __t.timestamp(),
  consumedStep: __t.string(),
  consumedRound: __t.u32(),
});
export type Note = __Infer<typeof Note>;

export const Objection = __t.object("Objection", {
  id: __t.u64(),
  questionId: __t.u64(),
  round: __t.u32(),
  bySlot: __t.string(),
  byLabel: __t.string(),
  targetOrdinal: __t.u32(),
  claim: __t.string(),
  issue: __t.string(),
  checkable: __t.bool(),
  severity: __t.u8(),
  status: __t.string(),
  resolution: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Objection = __Infer<typeof Objection>;

export const Paragraph = __t.object("Paragraph", {
  id: __t.u64(),
  questionId: __t.u64(),
  ordinal: __t.u32(),
  version: __t.u32(),
  text: __t.string(),
  status: __t.string(),
  causeType: __t.string(),
  causeId: __t.u64(),
  why: __t.string(),
  createdAt: __t.timestamp(),
  current: __t.bool(),
  heading: __t.string(),
});
export type Paragraph = __Infer<typeof Paragraph>;

export const Provider = __t.object("Provider", {
  id: __t.u32(),
  name: __t.string(),
  baseUrl: __t.string(),
  apiKey: __t.string(),
  enabled: __t.bool(),
  extra: __t.string(),
});
export type Provider = __Infer<typeof Provider>;

export const Question = __t.object("Question", {
  id: __t.u64(),
  roomId: __t.u64(),
  askedBy: __t.identity(),
  askedByName: __t.string(),
  text: __t.string(),
  state: __t.string(),
  round: __t.u32(),
  roundCap: __t.u32(),
  version: __t.u32(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  settledAt: __t.option(__t.timestamp()),
  wrapRequested: __t.bool(),
  callsUsed: __t.u32(),
  openObjections: __t.u32(),
  lastError: __t.string(),
  extraPasses: __t.u8(),
  contextSeen: __t.u32(),
});
export type Question = __Infer<typeof Question>;

export const Room = __t.object("Room", {
  id: __t.u64(),
  code: __t.string(),
  title: __t.string(),
  brief: __t.string(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  questionCount: __t.u32(),
  callsUsed: __t.u32(),
});
export type Room = __Infer<typeof Room>;

export const StepSchedule = __t.object("StepSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  questionId: __t.u64(),
  round: __t.u32(),
  step: __t.string(),
  slot: __t.string(),
  attempt: __t.u32(),
});
export type StepSchedule = __Infer<typeof StepSchedule>;

export const TeamQuestion = __t.object("TeamQuestion", {
  id: __t.u64(),
  questionId: __t.u64(),
  roomId: __t.u64(),
  text: __t.string(),
  answer: __t.string(),
  answeredByName: __t.string(),
  createdAt: __t.timestamp(),
  answeredAt: __t.option(__t.timestamp()),
});
export type TeamQuestion = __Infer<typeof TeamQuestion>;

export const WatchdogSchedule = __t.object("WatchdogSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type WatchdogSchedule = __Infer<typeof WatchdogSchedule>;

export const WelcomeSchedule = __t.object("WelcomeSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  requestId: __t.u64(),
});
export type WelcomeSchedule = __Infer<typeof WelcomeSchedule>;

